services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app-net
    deploy:
      placement:
        constraints:
          - node.labels.type == manager


  redis:
    image: redis:alpine
    networks:
      - app-net
    deploy:
      placement:
        constraints:
          - node.labels.type == manager

  worker:
    image: worker:latest
    environment:
      DB_SERVER: postgres  # Modifié pour correspondre au nom du service
      REDIS_HOST: redis
    networks:
      - app-net
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1  # Ajouté pour limiter à 1 replica par nœud
        constraints:
          - node.labels.type == worker
    depends_on:
      - db
      - redis

  vote:
    image: vote:latest
    ports:
      - "8080:8080"  # Changé de 5000:80 à 8080:8080
    environment:
      REDIS_HOST: redis
    networks:
      - app-net
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1  # Ajouté pour limiter à 1 replica par nœud
        constraints:
          - node.labels.type == worker
    depends_on:
      - redis

  result:
    image: result:latest
    ports:
      - "8888:8888"  # Changé de 5001:80 à 8888:8888
    environment:
      DB_SERVER: db
      REDIS_HOST: redis
    networks:
      - app-net
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1  # Ajouté pour limiter à 1 replica par nœud
        constraints:
          - node.labels.type == worker
    depends_on:
      - db
      - redis

networks:
  app-net:
    external: true
