services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-net

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-net
    depends_on:
      - worker

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker
    environment:
      DB_SERVER: db
      DB_PORT: 5432
      REDIS_HOST: redis
    restart: unless-stopped
    networks:
      - app-net
    depends_on:
      - db

  vote:
    build:
      context: ./vote
      dockerfile: dockerfile
    container_name: vote
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
    restart: unless-stopped
    networks:
      - app-net
    depends_on:
      - redis

  result:
    build:
      context: ./result
      dockerfile: Dockerfile
    container_name: result
    ports:
      - "8888:8888"
    environment:
      DB_SERVER: db
      DB_PORT: 5432
    restart: unless-stopped
    networks:
      - app-net
    depends_on:
      - db

volumes:
  db_data:
  redis_data:

networks:
  app-net:
